// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDummyData() {
  return window['go']['main']['App']['GetDummyData']();
}

export function GetImpedanceDummyData() {
  return window['go']['main']['App']['GetImpedanceDummyData']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
